[run]
build = "npm run build"

[gptengineer-app]
project_id = "c28d2536-b783-4004-8cb6-8eed7356a0ca"

[[gptengineer-app.openapi]]
url = "https://vdnhjxmsuykhvhnvjupi.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbmhqeG1zdXlraHZobnZqdXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDk4MjIyNjUsImV4cCI6MjAyNTM5ODI2NX0.byaihexABIEbRtnd1-n8R33kkt4lIwcB1xsX6P6PUA8\t"
